# vim: ft=sh
# Lauch things ... thats it. nice
# 'startx' uses sh and might require POSIX compliance.
# No bashisms pls

TARGET_WM="dwm"
WM_CMD="exec"

launch_scripts() {
    xorg_set_background &
    wm_launch_statusbar &

    eval "$(ssh-agent)"

    redshift -l "${DOTFILES_XORG_REDSHIFT_LOCATION:?redshift: missing location}" &>/dev/null &
    unclutter --ignore-scrolling --timeout 5 &
    dunst &
}

launch_host_specific() {
    # Some mobile/desktop specific stuff
    case "$(uname -n)" in
    'artbox' )
        xrandr --output DP-2 --primary --auto --left-of DVI-D-0 &
        ;;
    'box_mobile' )
        xorg_input_configure_touchpad
        setxkbmap us -option caps:escape &
        ;;
    esac
}

launch_pipewire() {
    pidof pipewire || {
        pipewire &
        pipewire -c '/etc/pipewire/pipewire-pulse.conf' &
        wireplumber &
    }
}

launch_host_specific
launch_scripts
launch_pipewire

case "$TARGET_WM" in
'dwm')
    exec dwm ;;
'penrose')
    exec "$HOME/projects/coding/rust/penrose_client/target/release/penrose_client" ;;
esac
