[cursor]
thickness = 0.01

[cursor.style]
blinking = "Off"
shape = "Beam"

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000

[window]
dynamic_padding = true

[window.padding]
x = 3
y = 3

[font]
size = 11

[font.bold]
family = "Comic Code Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Comic Code Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Comic Code Nerd Font"
style = "Italic"

[font.normal]
family = "Comic Code Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 3

[colors.primary]
background = "0x1d2021"
foreground = "0xd5c4a1"

[colors.bright]
black = "0x32302f"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.normal]
black = "0x32302f"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"
