[global]
password_cmd = "pass web/spotify/password"
username_cmd = "pass web/spotify/username"

use_mpris = true
backend = "rodio"
bitrate = 320

device_type = "computer"
device_name = "box_mobile"

cache_dir = "/home/haru/.cache/spotifyd"
