[global]
password_cmd = "pass web/spotify"
username_cmd = "pass web/spotify.user"
use_mpris = true
backend = "pulseaudio"
# device = "default"
device_type = "computer"
device_name = "box"
bitrate = 320
on_song_change_hook = "hook_sp_song_change"

cache_path = "/home/horo/.cache/spotifyd"
