default_font: &default_font "ComicCode Nerd Font:style=regular:size=15"
default_font_bold: &default_font_bold "ComicCode Nerd Font:style=bold:size=11"

color_background: &color_background 141617ff
color_background_highlight: &color_background_highlight 32302fff
color_highlight: &color_highlight 789984ff

bar:
  height: 20
  location: bottom
  spacing: 3
  font: *default_font
  background: *color_background

  left:
    - river:
        anchors:
          river_title: { string: { text: "{title}" }}

          tag_text:     &tag_text     { margin: 5, text: "{id}" }
          tag_actions:  &tag_actions  { margin: 5, on-click: "sh -c 'riverctl set-focused-tags $(( 1 << ({id} - 1) ))'" }
          tag_empty:    &tag_empty    { deco: {background: {color: *color_background } } }
          tag_focused:  &tag_focused  { deco: {background: {color: *color_highlight } }, font: *default_font_bold }
          tag_urgent:   &tag_urgent   { deco: {background: {color: ea6962ff } }, font: *default_font_bold }
          tag_occupied: &tag_occupied { deco: {background: {color: *color_background_highlight } } }

        title:
          - string: { margin: 5, text: "[{layout}]", deco: {background: { color: *color_background_highlight}}}
        content:
          map:
            conditions:
              # Reminder to make sure the order is correct.. see yambar-particles(5)
              (urgent):               { string: { <<: [ *tag_actions, *tag_text, *tag_urgent ]}}
              (focused):              { string: { <<: [ *tag_actions, *tag_text, *tag_focused]}}
              (occupied):             { string: { <<: [ *tag_actions, *tag_text, *tag_occupied]}}
              (~occupied && id <= 9): { string: { <<: [ *tag_actions, *tag_text, *tag_empty]}}
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "{app-id}", max: 30, foreground: *color_highlight }
                - string: {text: " {title}", max: 30}
  center:
    - mpris:
        identities:
          - "ncspot"
          - "spotify"
          - "firefox"
        content:
          - map:
              conditions:
                state != offline && title != "":
                  - list:
                      spacing: 5
                      items:
                        - string: {text: "{artist}", max: 30 }
                        - string: {text: "-" }
                        - string: {text: "{title}", max: 30 }
                  # - map:
                  #     conditions:
                  #       pos != "":
                  #         - string: {text: " " }
                  #         - string: {text: "{pos} / {end}", max: 30 }
                  #         - list:
                  #             items:
                  #               - progress-bar:
                  #                   tag: "elapsed"
                  #                   length: 10
                  #                   start: { string: { text: "[" } }
                  #                   end: { string: { text: "]" } }
                  #                   fill: { string: { text: "=" } }
                  #                   empty: { string: { text: " " } }
                  #                   indicator: { string: { text: ">" } }
                  - map:
                      conditions:
                        shuffle: { string: { text: "" } }
                  - map:
                      conditions:
                        loop == Playlist: { string: { text: "" } }

  right:
    - network:
        poll-interval: 2500
        content:
          map:
            margin: 8
            deco: { background: { color: *color_background_highlight}}
            conditions:
              type == ether || type == wlan:
                map:
                  conditions:
                    state == up:
                      list:
                        items:
                          - string: {max: 6, text: "{name}"}
                          - string: {text: ": {state} [{ipv4}]"}
                          - string: {text: "{ul-speed:mib}"}
                          - string: {text: "{dl-speed:mib}"}

    - cpu:
        poll-interval: 2500
        content:
          map:
            conditions:
              id < 0:
                list:
                  margin: 8
                  deco: { background: { color: *color_background_highlight}}
                  items:
                    - string: {text: "CPU:"}
                    - string: {text: "{cpu:02:}%"}

    - mem:
        poll-interval: 2500
        content:
          list:
            deco: { background: { color: *color_background_highlight}}
            margin: 8
            items:
              - string: {text: "MEM:"}
              - string: {text: "{used::mib}"}
              - string: {text: "/"}
              - string: {text: "{total:mib}"}
              - string: {text: "[{percent_used:%}%]"}
    - clock:
        time-format: "%R"
        date-format: "%a %d %b %Y"
        content:
          list:
            margin: 8
            deco: { background: { color: *color_background_highlight}}
            items:
              - string: {text: "{date}", right-margin: 5}
              - string: {text: "┃"}
              - string: {text: "{time}", right-margin: 10}
