#!/usr/bin/sh

# A little setup script for my dotfiles. This
# allows me to cange, sync and update them on 
# the fly.

readonly SCRIPT_PATH="$(dirname "$(readlink -f $0)")"
readonly TARGET_PATH="$HOME/.config"
readonly DIRS_LIST_PATH="$(find "$SCRIPT_PATH" -mindepth 1 -maxdepth 1 -type d -not -name '.*')"

link_single() {
	ln -s "$1" "$2"
}
export -f link_single
link_list() {
	echo "$1" | xargs -I{} sh -c 'link_single "$@"' - '{}' "$2"
}

main() {
	echo FILES: $DIRS_LIST_PATH
	mkdir $TARGET_PATH
	link_list "$DIRS_LIST_PATH" "$TARGET_PATH"
}

main
