#!/usr/bin/sh

PLAYERCTL="playerctl"
PLAYER="ncspot,spotifyd,firefox"
IGNORE=""

run() {
    playerctl \
        --ignore-player="$IGNORE" \
        --player="$PLAYER" \
        $@
}
display_banner() {
    local artist="$(playerctl metadata artist)"
    local title="$(playerctl metadata title)"
    local cover="$(playerctl metadata artUrl)"
}

if [ -z "$1" ] && [ "$_cmd" != 'next' ] && [ "$_cmd" != 'previous' ] && [ "$_cmd" != 'play-pause' ]; then
    exit 1
fi

run $1
#display_banner
