#!/usr/bin/sh

PLAYERCTL="playerctl"
PLAYER="ncspot,spotifyd,spotify,firefox"

run() {
    playerctl \
        --ignore-player="$IGNORE" \
        --player="$PLAYER" \
        $@
    }

display_banner() {
    eval $(run metadata --format 'META_ARTIST="{{xesam:artist}}";META_ALBUM="{{xesam:album}}";META_TITLE="{{xesam:title}}";META_ART_URL="{{mpris:artUrl}}"')
    notify-send --icon="$META_ART_URL" "$META_TITLE" "$META_ARTIST"
}

if [ -z "$1" ] && [ "$_cmd" != 'next' ] && [ "$_cmd" != 'previous' ] && [ "$_cmd" != 'play-pause' ]; then
    exit 1
fi

run $1
display_banner
