source-file $HOME/dotfiles/config/tmux/theme_gruvbox_medium.conf

# OPTIONS
set-option -g focus-events on
set-option -sa terminal-overrides ',xterm-256color:RGB'
set-option -g default-terminal 'tmux-256color'
set-option -g renumber-windows on
set-option -g escape-time 0

set-option -g prefix C-Space
set-window-option -g mode-keys vi

# KEYBINDINGS
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

unbind-key -T copy-mode-vi Space
unbind-key -T copy-mode-vi Enter
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"`

unbind-key Space
bind-key Space select-window -T

unbind-key x
bind-key x kill-pane

